name: talker_sqflite_logger
description: sqflite library logger on talker base.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  sqflite: ^2.3.0
  sqflite_common: ^2.5.0+2
  talker: ^3.2.0

dev_dependencies:
  mocktail: ^1.0.0
  sqflite_common_ffi: ^2.3.2
  test: ^1.19.2
  very_good_analysis: ^5.1.0
