name: talker_sqflite_logger
description: sqflite library logger on talker base.
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  sqflite: ^2.3.2
  sqflite_common: ^2.5.3
  talker: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  sqflite_common_ffi: ^2.3.2
  very_good_analysis: ^5.1.0
